// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestForge.Infrastructure.Persistence;

#nullable disable

namespace TestForge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TestForgeDbContext))]
    partial class TestForgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestForge.Domain.Entities.TestRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error_message");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("repository_url");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_test_runs_created_at_utc");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_test_runs_status");

                    b.ToTable("test_runs", (string)null);
                });

            modelBuilder.Entity("TestForge.Domain.Entities.TestRunReport", b =>
                {
                    b.Property<Guid>("TestRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_run_id");

                    b.Property<int?>("BuildExitCode").HasColumnType("integer").HasColumnName("build_exit_code");
                    b.Property<long?>("BuildDurationMilliseconds").HasColumnType("bigint").HasColumnName("build_duration_ms");
                    b.Property<string>("BuildProjectPath").HasMaxLength(2048).HasColumnType("character varying(2048)").HasColumnName("build_project_path");
                    b.Property<string>("BuildStandardError").HasColumnType("text").HasColumnName("build_standard_error");
                    b.Property<string>("BuildStandardOutput").HasColumnType("text").HasColumnName("build_standard_output");
                    b.Property<int?>("FailedCount").HasColumnType("integer").HasColumnName("failed_count");
                    b.Property<int?>("PassedCount").HasColumnType("integer").HasColumnName("passed_count");
                    b.Property<int?>("SkippedCount").HasColumnType("integer").HasColumnName("skipped_count");
                    b.Property<long?>("TestDurationMilliseconds").HasColumnType("bigint").HasColumnName("test_duration_ms");
                    b.Property<int?>("TestExitCode").HasColumnType("integer").HasColumnName("test_exit_code");
                    b.Property<string>("TestProjectPaths").IsRequired().HasColumnType("text").HasColumnName("test_project_paths");
                    b.Property<string>("TestStandardError").HasColumnType("text").HasColumnName("test_standard_error");
                    b.Property<string>("TestStandardOutput").HasColumnType("text").HasColumnName("test_standard_output");

                    b.HasKey("TestRunId");
                    b.ToTable("test_run_reports", (string)null);
                });

            modelBuilder.Entity("TestForge.Domain.Entities.TestRunReport", b =>
                {
                    b.HasOne("TestForge.Domain.Entities.TestRun", null)
                        .WithOne()
                        .HasForeignKey("TestForge.Domain.Entities.TestRunReport", "TestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
